// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // 迁移 / introspection 走 session pooler 直连（DIRECT_URL，端口 5432）；
  // 运行时业务连接由 PrismaClient 读 DATABASE_URL（transaction pooler，6543）
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
